project:
  type: book
  output-dir: docs

book:
  title: "course sequence analysis"
  author: "Tim Ransom"
  date: "2/14/2023"
  chapters:
    - index.qmd
    - intro-to-midfield.qmd
    - course-graphs.qmd
    - graph-properties.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-block-background: true
    code-fold: true
  # pdf:
  #   documentclass: scrreprt

execute:
  cache: true
  freeze: auto  # re-render only when source changes
